### ISSUE TITLE
Include local library modifications in Details and EditEntry fragments

### ISSUE THREAD

**Issue by Drumber** [Drumber/Kitsune#16]
Locally stored library modifications are not considered when displaying the library status in the DetailsFragment and as well all other values in EditEntryFragment.

This can be confusing for the user since the LibraryFragment shows library entries including local/offline changes.

It should be considered to have EditEntryFragment not save failed library updates locally by default, but display a dialog with the option to discard or store library modifications.

## Task list
- [ ] DetailsFragment includes local library modifications
- [ ] EditEntryFragment includes local library modifications
- [ ] EditEntryFragment shows dialog on push failure with the option to discard or store changes locally

**Comment by RokeJulianLockhart** [comment]
@Drumber, does this issue track caching library modifications performed offline, for synchronisation when connection is restored?

**Comment by Drumber** [comment]
Caching and syncing offline modifications already work in Kitsune. This issue addresses some places in the UI where cached offline modifications are not reflected. In particular, the editing dialog of a library entry does not currently support offline modifications.
